   name: Deploy to Lightsail

   on:
     push:
       branches:
         - main

   jobs:
     deploy:
       runs-on: ubuntu-latest

       steps:
       - name: Checkout code
         uses: actions/checkout@v2

       - name: Set up SSH
         uses: webfactory/ssh-agent@v0.5.3
         with:
           ssh-private-key: ${{ secrets.LIGHTSAIL_SSH_KEY }}

       - name: Deploy to Lightsail
         run: |
           ssh -o StrictHostKeyChecking=no ubuntu@54.221.239.111 << 'EOF'
             cd /home/ubuntu/multidepravation-data-viewer
             git pull origin master
             # Add any additional deployment commands here
             # e.g., npm install, systemctl restart your-app.service, etc.
           EOF
