name: Deploy to Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Lightsail
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: 54.221.239.111
        username: ubuntu
        key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
        script: |
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          cd /home/ubuntu/multidepravation-data-viewer
          git pull origin main
          python3 app.py
